# Reference:
# https://docs.blender.org/manual/en/dev/advanced/extensions/getting_started.html#manifest

schema_version = "1.0.0"

id = "find_bad_tracks"
version = "0.0.1"
name = "Find Bad Tracks"

# NOTE: The tagline can be at most 64 characters long
tagline = "Highlight motion tracks that move in suspicious directions"
maintainer = "Johan Walles <johan.walles@gmail.com>"

type = "add-on"

website = "https://github.com/walles/find_bad_motion_tracks"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Tracking"]

# Must be at least "4.2.0" to go onto https://extensions.blender.org.
blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix).
#
# GPLv3 recommended here:
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = ["SPDX:GPL-3.0-or-later"]
